[tool.poetry]
name = "speckle"
version = "0.1.0"
description = ""
authors = [
    "Izzy Lyseggen <izzy.lyseggen@gmail.com>",
    "Matteo Cominetti <matteo@speckle.systems>",
    "Gergő Jedlicska <gergo@jedlicska.com>"
]
license = "SEE LICENSE IN readme.md"

[tool.poetry.dependencies]
python = "^3.6"
pydantic = "^1.7.3"
gql = "^3.0.0a5"
aiohttp = "^3.7.3"
appdirs = "^1.4.4"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
pytest = "^6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
