version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build:
    docker:
      - image: "cimg/python:<<parameters.tag>>"
      - image: "circleci/node:12"
      - image: "circleci/redis:6"
      - image: "circleci/postgres:12"
        environment:
          POSTGRES_DB: speckle2_test
          POSTGRES_PASSWORD: speckle
          POSTGRES_USER: speckle
      - image: "speckle/speckle-server:5f8cf11cba07ea6a54000243f9cb343b61cbba13"
        command: ["bash", "-c", "/wait && node bin/www"]
        environment:
          POSTGRES_URL: "localhost"
          POSTGRES_USER: "speckle"
          POSTGRES_PASSWORD: "speckle"
          POSTGRES_DB: "speckle2_test"
          REDIS_URL: "redis://localhost"
          SESSION_SECRET: "keyboard cat"
          STRATEGY_LOCAL: "true"
          CANONICAL_URL: "http://localhost:3000"
          WAIT_HOSTS: localhost:5432, localhost:6379
    parameters:
      tag:
        default: "3.8"
        type: string
    steps:
      - checkout
      - run: python --version
      - run:
          command: python -m pip install --upgrade pip
          name: upgrade pip
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run pytest --version

workflows:
  main:
    jobs:
      - build:
          matrix:
            parameters:
              tag: ["3.6", "3.7", "3.8", "3.9"]
