version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run: python -m pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            pytest --version
          name: Test

workflows:
  main:
    jobs:
      - build
      - python/test:
          pkg-manager: pip
          test-tool: pytest
